[package]
name = "cttm"
version = "0.1.0"
edition = "2024"
readme = "../README.md"
description = "CTTM is Compile-Time Template engine"
license = "MIT"
repository = "https://github.com/sharp0802/cttm"

[features]
build = []

[dependencies]
glob = "0.3.3"
thiserror = "2.0.17"
